export const ACTION_MESSAGE = {
    NOTEBOOK_SAVE: 'NOTEBOOK_SAVE',
    NOTEBOOK_LIST: 'NOTEBOOK_LIST',
    NOTEBOOK_DELETE: 'NOTEBOOK_DELETE',
    NOTE_SAVE: 'NOTE_SAVE',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_DELETE: 'NOTE_DELETE',
    NOTE_MOVE: 'NOTE_MOVE',
    TAG_LIST: 'TAG_LIST',
}