const IPCMESSAGE = {
    NOTEBOOK_LIST: 'NOTEBOOK_LIST',
    NOTEBOOK_SAVE: 'NOTEBOOK_SAVE',
    NOTEBOOK_DELETE: 'NOTEBOOK_DELETE',
    TAGS_LIST: 'TAGS_LIST',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_DELETE: 'NOTE_DELETE',
    NOTE_SAVE: 'NOTE_SAVE',
    NOTE_MOVE:'NOTE_MOVE',
};

module.exports = IPCMESSAGE