const IPCMESSAGE = {
    NOTEBOOK_LIST: 'NOTEBOOK_LIST',
    NOTEBOOK_SAVE: 'NOTEBOOK_SAVE',
    NOTEBOOK_DELETE: 'NOTEBOOK_DELETE',
    TAGS_LIST: 'TAGS_LIST',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_DELETE: 'NOTE_DELETE',
    NOTE_SAVE: 'NOTE_SAVE',
    NOTE_MOVE: 'NOTE_MOVE',
    NOTE_EXPORT_PDF: 'NOTE_EXPORT_PDF',
    NOTE_EXPORT_FILE: 'NOTE_EXPORT_FILE',
    MENU_SELECT_ALL: 'MENU_SELECT_ALL',
    MENU_NOTE_NEW: 'MENU_NOTE_NEW',
    MENU_NOTE_SAVE: 'MENU_NOTE_SAVE',
};

module.exports = IPCMESSAGE