export const ACTION_MESSAGE = {
    NOTE_SAVE: 'NOTE_SAVE',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_DELETE: 'NOTE_DELETE',
    CONTENT_SAVE:'CONTENT_SAVE',
    CONTENT_LIST:'CONTENT_LIST',
    CONTENT_DELETE:'CONTENT_DELETE',
}